{{- if .Values.apiServer.autoscaling.enabled }}
apiVersion: {{ include "apiVersion.autoscaling" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "apiServer.fullname" . }}
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "apiServer.fullname" . }}
  minReplicas: {{ .Values.apiServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiServer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apiServer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.apiServer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apiServer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.apiServer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
