{{- if .Values.apiServer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apiServer.serviceAccountName" . }}
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
  {{- with .Values.apiServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
