apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiServer.fullname" . }}
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apiServer.selectorLabels" . | nindent 4 }}
