apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "urlshortener.fullname" . }}
  labels:
    {{- include "urlshortener.labels" . | nindent 4 }}
spec:
  {{- if not .Values.urlshortener.autoscaling.enabled }}
  replicas: {{ .Values.urlshortener.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "urlshortener.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.urlshortener.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "urlshortener.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.urlshortener.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "urlshortener.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.urlshortener.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.urlshortener.terminationGracePeriodSeconds }}
      containers:
        #- name: kube-rbac-proxy
        #  securityContext:
        #    allowPrivilegeEscalation: false
        #  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
        #  imagePullPolicy: ifNotPresent
        #  args:
        #    - --secure-listen-address=0.0.0.0:8443
        #    - --upstream=http://127.0.0.1:8080/
        #    - --logtostderr=true
        #    - --v=0
        #  ports:
        #    - containerPort: 8443
        #      name: https
        #      protocol: TCP
        #  resources:
        #    limits:
        #      cpu: 500m
        #      memory: 128Mi
        #    requests:
        #      cpu: 5m
        #      memory: 64Mi
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.urlshortener.securityContext | nindent 12 }}
          image: "{{ .Values.urlshortener.image.repository }}:{{ .Values.urlshortener.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.urlshortener.image.pullPolicy }}
          command:
            - /urlshortener
          args:
            - --health-probe-bind-address=:8081
            - --bind-address=:8123
            - --metrics-bind-address=:{{ .Values.apiServer.metrics.service.servicePort }}

          {{- with .Values.urlshortener.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.urlshortener.service.port }}
              protocol: TCP
            {{- if .Values.urlshortener.metrics.enabled }}
            - name: {{ .Values.urlshortener.metrics.service.portName }}
              containerPort: {{ .Values.urlshortener.metrics.service.servicePort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.urlshortener.resources | nindent 12 }}
          env:
            {{- with .Values.global.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.urlshortener.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.global.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.urlshortener.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.urlshortener.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.urlshortener.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.urlshortener.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
