{{- if .Values.urlshortener.pdb.enabled }}
apiVersion: {{ include "apiVersion.pdb" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "urlshortener.fullname" . }}
  labels:
    {{- include "urlshortener.labels" . | nindent 6 }}
    {{- with .Values.urlshortener.pdb.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.urlshortener.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  {{- with .Values.urlshortener.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.urlshortener.pdb.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "urlshortener.selectorLabels" . | nindent 6 }}
{{- end }}