{{- if .Values.urlshortener.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "urlshortener.serviceAccountName" . }}
  labels:
    {{- include "urlshortener.labels" . | nindent 4 }}
  {{- with .Values.urlshortener.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
