apiVersion: v1
kind: Service
metadata:
  name: {{ include "urlshortener.fullname" . }}
  labels:
    {{- include "urlshortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.urlshortener.service.type }}
  ports:
    - port: {{ .Values.urlshortener.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "urlshortener.selectorLabels" . | nindent 4 }}
